---
title: "Blood Lead Level Exploration"
author: Liz Peterson
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv"),)
stl_lead <- stl_lead %>% clean_names()
```

```{r}
names(stl_lead)
dim(stl_lead)
summary(stl_lead)
```

```{r}
stl_lead_prop <- data.frame(stl_lead) %>% dplyr::mutate(prop_white = white/total_pop)
names(stl_lead_prop)
```

There is a higher proportion of non-white children that have elevated lead levels in their blood than white children. 
```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = prop_white)) +
  geom_point(color = "blue", alpha = 0.5, size = 2) +
  theme_minimal() +
  labs(title = "Percentage of Children with Elevated Blood Lead Levels",
       x = "Percent of Children with Elevated Blood Lead Levels",
       y = "Precent White Children")
stl_lead_plot
```

```{r}
ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)
```

```{r}
ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(color = "blue", fill = "pink") +
  labs(title = "Frequency of Children with Elevated Blood Lead Levels",
       x = "Percent of Children with Elevated Blood Lead Levels",
       y = "Count")
```

```{r}
ggsave(here::here("figs", "stl_hist.jpg"), height = 5, width = 6)
```


